// LOCALHOST
###
GET http://localhost:8080/contacts 
###
GET http://localhost:8080/contacts/6636fc6f875d0dc5921cc709
###
GET http://localhost:8080/contacts/6636fc6f875d0dc5921cc70a
### 
GET http://localhost:8080/contacts/6636fc6f875d0dc5921cc70b

// PRODUCTION Deploy 
### 
GET https://cse341-1-802v.onrender.com/contacts
### 
GET https://cse341-1-802v.onrender.com/contacts/6636fc6f875d0dc5921cc709
### 
GET https://cse341-1-802v.onrender.com/contacts/6636fc6f875d0dc5921cc70a
### 
GET https://cse341-1-802v.onrender.com/contacts/6636fc6f875d0dc5921cc70b